"""Shared fixtures for the golden suite.

``fixture_bundle`` runs the *real* aggregate builder once per session against the
frozen corpus, into a temp dir. Layer B asserts the derived tables directly;
Layer C points ``api.figures`` at this bundle and asserts plotted arrays.

Reference assets (AI β, labour force, wage-by-education, geojson) are read by the
viz layer from repo-anchored paths, NOT from this bundle — so the tests exercise
the real committed assets, exactly as production does.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

# Make the repo root importable so Layer C can ``import api.figures`` regardless
# of where pytest is launched (there is no repo-wide pytest config, and this
# package carries no __init__.py for pytest to walk up from).
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from jobads_dashboard.dashboard.prepare import refresh_dashboard_data
from jobads_dashboard.viz.datasource import DataSource

# The committed frozen corpus (tests/fixtures/golden_corpus), regenerated by
# tests/fixtures/build_corpus.py. Resolved by path so the suite never needs the
# `tests` directory to be an importable package.
CORPUS_ROOT = Path(__file__).resolve().parents[1] / "fixtures" / "golden_corpus"


@pytest.fixture(scope="session")
def corpus_root() -> Path:
    return CORPUS_ROOT


@pytest.fixture(scope="session")
def fixture_bundle(tmp_path_factory) -> Path:
    out = tmp_path_factory.mktemp("golden_bundle")
    refresh_dashboard_data(
        source_root=CORPUS_ROOT,
        output_root=out,
        top_markets_per_province=10,
        skills_top_k=10,
        posting_lookup_recent_months=0,
    )
    return out


@pytest.fixture(scope="session")
def ds(fixture_bundle) -> DataSource:
    return DataSource(fixture_bundle)
